### ISSUE TITLE
imageEditorAfterWriteImage prop of React Filepond component can't receive a promise 

### ISSUE THREAD

**Issue by ockam** [pqina/filepond-plugin-image-editor#1]
Currently experimenting with Pintura and Filepond inside a React app.

Trying to implement the [thumbnail example from the doc](https://pqina.nl/pintura/docs/v8/installation/filepond/#imageeditorafterwriteimage), but the `imageEditorAfterWriteImage` prop of `Filepond` React component doesn't accept promises.

Is there another way to accomplish this with the React component?

**Comment by rikschennink** [comment]
It's probably a problem with the TypeScript declaration file, you can add a `//@ts-ignore` to work around it for now, I'll add it to my todo list.

**Comment by rikschennink** [comment]
Just pushed a new version of the image-editor plugin, should fix the issue.

**Comment by ockam** [comment]
Wow! That was fast. Thanks!

**Comment by ockam** [comment]
Works as expected. Closing the issue.

**Comment by rikschennink** [comment]
Glad to hear that :)

Kind regards,

Rik | PQINA

PQINA BV
Sint Willibrordusstraat 16
5502 BH Veldhoven
The Netherlands
